### ISSUE TITLE
Unable to install dependencies due to FileNotFoundError exception for PyYAML package

### ISSUE THREAD

**Issue by jeffshurtliff** [jeffshurtliff/khoros#11]
Builds of the source package fail during the dependency installation phase

``` python
2020-07-18T03:15:31.6592138Z ##[group]Run python -m pip install --upgrade pip
2020-07-18T03:15:31.6592392Z python -m pip install --upgrade pip
2020-07-18T03:15:31.6592573Z pip install -r requirements.txt
2020-07-18T03:15:31.6637776Z shell: /bin/bash -e {0}
2020-07-18T03:15:31.6637961Z env:
2020-07-18T03:15:31.6638132Z   pythonLocation: /opt/hostedtoolcache/Python/3.7.8/x64
2020-07-18T03:15:31.6638308Z ##[endgroup]
2020-07-18T03:15:32.3844189Z Requirement already up-to-date: pip in /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages (20.1.1)
2020-07-18T03:15:33.3218938Z Collecting pytest
2020-07-18T03:15:33.3814775Z   Downloading pytest-5.4.3-py3-none-any.whl (248 kB)
2020-07-18T03:15:33.5394006Z Collecting alabaster==0.7.12
2020-07-18T03:15:33.5536555Z   Downloading alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
2020-07-18T03:15:33.6161463Z Collecting Babel==2.8.0
2020-07-18T03:15:33.6320698Z   Downloading Babel-2.8.0-py2.py3-none-any.whl (8.6 MB)
2020-07-18T03:15:34.5675153Z Collecting certifi==2019.11.28
2020-07-18T03:15:34.5828781Z   Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
2020-07-18T03:15:34.5984843Z Requirement already satisfied: chardet==3.0.4 in /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg (from -r requirements.txt (line 5)) (3.0.4)
2020-07-18T03:15:34.6488753Z Collecting colorama==0.4.3
2020-07-18T03:15:34.6642277Z   Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
2020-07-18T03:15:34.7209366Z Collecting dnspython==1.16.0
2020-07-18T03:15:34.7355602Z   Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
2020-07-18T03:15:34.8137380Z Collecting docutils==0.16
2020-07-18T03:15:34.8319014Z   Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
2020-07-18T03:15:34.9273708Z Collecting idna==2.8
2020-07-18T03:15:34.9420936Z   Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
2020-07-18T03:15:34.9878132Z Collecting imagesize==1.2.0
2020-07-18T03:15:35.0035337Z   Downloading imagesize-1.2.0-py2.py3-none-any.whl (4.8 kB)
2020-07-18T03:15:35.0598507Z Collecting Jinja2==2.11.1
2020-07-18T03:15:35.0747337Z   Downloading Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)
2020-07-18T03:15:35.1439486Z Collecting MarkupSafe==1.1.1
2020-07-18T03:15:35.1593339Z   Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
2020-07-18T03:15:35.1975956Z Collecting ntfsutils==0.1.4
2020-07-18T03:15:35.2120653Z   Downloading ntfsutils-0.1.4.tar.gz (7.3 kB)
2020-07-18T03:15:36.0146070Z Collecting numpy==1.18.1
2020-07-18T03:15:36.0299813Z   Downloading numpy-1.18.1-cp37-cp37m-manylinux1_x86_64.whl (20.1 MB)
2020-07-18T03:15:37.3562704Z Collecting oauthlib==3.1.0
2020-07-18T03:15:37.3723681Z   Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
2020-07-18T03:15:37.4663831Z Collecting packaging==20.1
2020-07-18T03:15:37.4817808Z   Downloading packaging-20.1-py2.py3-none-any.whl (36 kB)
2020-07-18T03:15:37.7989772Z Collecting pandas==1.0.1
2020-07-18T03:15:37.8221362Z   Downloading pandas-1.0.1-cp37-cp37m-manylinux1_x86_64.whl (10.1 MB)
2020-07-18T03:15:38.6598632Z Collecting protobuf==3.6.1
2020-07-18T03:15:38.6833120Z   Downloading protobuf-3.6.1-cp37-cp37m-manylinux1_x86_64.whl (1.1 MB)
2020-07-18T03:15:39.0308028Z Collecting psutil==5.7.0
2020-07-18T03:15:39.0496204Z   Downloading psutil-5.7.0.tar.gz (449 kB)
2020-07-18T03:15:40.1352590Z Collecting Pygments==2.5.2
2020-07-18T03:15:40.1535958Z   Downloading Pygments-2.5.2-py2.py3-none-any.whl (896 kB)
2020-07-18T03:15:40.3495021Z Collecting pyparsing==2.4.6
2020-07-18T03:15:40.3648251Z   Downloading pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
2020-07-18T03:15:40.4190107Z Collecting python-dateutil==2.8.1
2020-07-18T03:15:40.4339957Z   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
2020-07-18T03:15:40.6014145Z Collecting pytz==2019.3
2020-07-18T03:15:40.6203443Z   Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
2020-07-18T03:15:40.8128934Z Collecting PyYAML==5.3
2020-07-18T03:15:40.8307786Z   Downloading PyYAML-5.3.tar.gz (268 kB)
2020-07-18T03:15:41.2790474Z Requirement already satisfied: requests==2.23.0 in /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg (from -r requirements.txt (line 25)) (2.23.0)
2020-07-18T03:15:41.3295995Z Collecting requests-oauthlib==1.3.0
2020-07-18T03:15:41.3451855Z   Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
2020-07-18T03:15:41.4137874Z Collecting requests-toolbelt==0.9.1
2020-07-18T03:15:41.4288467Z   Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
2020-07-18T03:15:41.4947081Z Collecting six==1.14.0
2020-07-18T03:15:41.5110202Z   Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
2020-07-18T03:15:41.5511877Z Collecting snowballstemmer==2.0.0
2020-07-18T03:15:41.5664345Z   Downloading snowballstemmer-2.0.0-py2.py3-none-any.whl (97 kB)
2020-07-18T03:15:41.7269790Z Collecting Sphinx==2.3.1
2020-07-18T03:15:41.7463929Z   Downloading Sphinx-2.3.1-py3-none-any.whl (2.7 MB)
2020-07-18T03:15:42.0380935Z Collecting sphinxcontrib-applehelp==1.0.1
2020-07-18T03:15:42.0526364Z   Downloading sphinxcontrib_applehelp-1.0.1-py2.py3-none-any.whl (121 kB)
2020-07-18T03:15:42.1299580Z Collecting sphinxcontrib-devhelp==1.0.1
2020-07-18T03:15:42.1443653Z   Downloading sphinxcontrib_devhelp-1.0.1-py2.py3-none-any.whl (84 kB)
2020-07-18T03:15:42.2275244Z Collecting sphinxcontrib-htmlhelp==1.0.2
2020-07-18T03:15:42.2438920Z   Downloading sphinxcontrib_htmlhelp-1.0.2-py2.py3-none-any.whl (96 kB)
2020-07-18T03:15:42.3260310Z Collecting sphinxcontrib-jsmath==1.0.1
2020-07-18T03:15:42.3405243Z   Downloading sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
2020-07-18T03:15:42.4198697Z Collecting sphinxcontrib-qthelp==1.0.2
2020-07-18T03:15:42.4358028Z   Downloading sphinxcontrib_qthelp-1.0.2-py2.py3-none-any.whl (90 kB)
2020-07-18T03:15:42.5170552Z Collecting sphinxcontrib-serializinghtml==1.1.3
2020-07-18T03:15:42.5314537Z   Downloading sphinxcontrib_serializinghtml-1.1.3-py2.py3-none-any.whl (89 kB)
2020-07-18T03:15:42.6321561Z Collecting urllib3==1.25.8
2020-07-18T03:15:42.6480820Z   Downloading urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
2020-07-18T03:15:42.6811203Z Requirement already satisfied: attrs>=17.4.0 in /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/attrs-19.3.0-py3.7.egg (from pytest->-r requirements.txt (line 1)) (19.3.0)
2020-07-18T03:15:42.8046733Z Collecting py>=1.5.0
2020-07-18T03:15:42.8203867Z   Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
2020-07-18T03:15:42.8967926Z Collecting wcwidth
2020-07-18T03:15:42.9123552Z   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
2020-07-18T03:15:43.0000420Z Collecting more-itertools>=4.0.0
2020-07-18T03:15:43.0151075Z   Downloading more_itertools-8.4.0-py3-none-any.whl (43 kB)
2020-07-18T03:15:43.0413128Z Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/importlib_metadata-1.7.0-py3.7.egg (from pytest->-r requirements.txt (line 1)) (1.7.0)
2020-07-18T03:15:43.0931011Z Collecting pluggy<1.0,>=0.12
2020-07-18T03:15:43.1083991Z   Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
2020-07-18T03:15:43.1348551Z Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages (from ntfsutils==0.1.4->-r requirements.txt (line 13)) (47.1.0)
2020-07-18T03:15:43.1637840Z Requirement already satisfied: zipp>=0.5 in /opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/zipp-3.1.0-py3.7.egg (from importlib-metadata>=0.12; python_version < "3.8"->pytest->-r requirements.txt (line 1)) (3.1.0)
2020-07-18T03:15:43.1719091Z Building wheels for collected packages: ntfsutils, psutil, PyYAML
2020-07-18T03:15:43.1729230Z   Building wheel for ntfsutils (setup.py): started
2020-07-18T03:15:44.5314681Z   Building wheel for ntfsutils (setup.py): finished with status 'done'
2020-07-18T03:15:44.5322480Z   Created wheel for ntfsutils: filename=ntfsutils-0.1.4-py3-none-any.whl size=9517 sha256=2470ab8144d154bd9da9b413283ad4db37ad941b516c1378f9b0a29d9e667d53
2020-07-18T03:15:44.5323334Z   Stored in directory: /home/runner/.cache/pip/wheels/0a/58/0a/0e8c6e28b1c3c6ee68c36200701e075f047ef4c15ad5b4046c
2020-07-18T03:15:44.5339340Z   Building wheel for psutil (setup.py): started
2020-07-18T03:15:46.4396104Z   Building wheel for psutil (setup.py): finished with status 'done'
2020-07-18T03:15:46.4409499Z   Created wheel for psutil: filename=psutil-5.7.0-cp37-cp37m-linux_x86_64.whl size=276629 sha256=545e1e81bd0ae93782c25d050c0f8ce7e2307151fe9956323376c415e26df530
2020-07-18T03:15:46.4410900Z   Stored in directory: /home/runner/.cache/pip/wheels/b6/e7/50/aee9cc966163d74430f13f208171dee22f11efa4a4a826661c
2020-07-18T03:15:46.4425175Z   Building wheel for PyYAML (setup.py): started
2020-07-18T03:15:46.8280541Z   Building wheel for PyYAML (setup.py): finished with status 'done'
2020-07-18T03:15:46.8287208Z   Created wheel for PyYAML: filename=PyYAML-5.3-cp37-cp37m-linux_x86_64.whl size=44228 sha256=d2ebb8005cdf245f10d9c4593518467cb3de28226d042e3be7aff92c573fa341
2020-07-18T03:15:46.8287989Z   Stored in directory: /home/runner/.cache/pip/wheels/8a/55/a4/c0a81d27c33462cfdcb904db018f5550197e88b2b6b85beed2
2020-07-18T03:15:46.8294257Z Successfully built ntfsutils psutil PyYAML
2020-07-18T03:15:47.0750974Z ERROR: aws-sam-cli 0.53.0 has requirement python-dateutil<2.8.1,~=2.6, but you'll have python-dateutil 2.8.1 which is incompatible.
2020-07-18T03:15:47.0752938Z Installing collected packages: pyparsing, six, packaging, py, wcwidth, more-itertools, pluggy, pytest, alabaster, pytz, Babel, certifi, colorama, dnspython, docutils, idna, imagesize, MarkupSafe, Jinja2, ntfsutils, numpy, oauthlib, python-dateutil, pandas, protobuf, psutil, Pygments, PyYAML, requests-oauthlib, requests-toolbelt, snowballstemmer, sphinxcontrib-qthelp, sphinxcontrib-devhelp, sphinxcontrib-htmlhelp, sphinxcontrib-applehelp, sphinxcontrib-serializinghtml, sphinxcontrib-jsmath, Sphinx, urllib3
2020-07-18T03:15:47.0754024Z ERROR: botocore 1.16.26 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
2020-07-18T03:15:47.1317646Z   Attempting uninstall: six
2020-07-18T03:15:47.1323498Z     Found existing installation: six 1.15.0
2020-07-18T03:15:47.1332389Z     Uninstalling six-1.15.0:
2020-07-18T03:15:47.1891738Z       Successfully uninstalled six-1.15.0
2020-07-18T03:15:47.5957775Z   Attempting uninstall: pytz
2020-07-18T03:15:47.5963402Z     Found existing installation: pytz 2020.1
2020-07-18T03:15:47.5971115Z     Uninstalling pytz-2020.1:
2020-07-18T03:15:47.6447784Z       Successfully uninstalled pytz-2020.1
2020-07-18T03:15:48.5372949Z   Attempting uninstall: certifi
2020-07-18T03:15:48.5378310Z     Found existing installation: certifi 2020.6.20
2020-07-18T03:15:48.5388499Z     Uninstalling certifi-2020.6.20:
2020-07-18T03:15:48.5936251Z       Successfully uninstalled certifi-2020.6.20
2020-07-18T03:15:48.7868196Z   Attempting uninstall: docutils
2020-07-18T03:15:48.7875586Z     Found existing installation: docutils 0.15.2
2020-07-18T03:15:48.7910025Z     Uninstalling docutils-0.15.2:
2020-07-18T03:15:48.8432217Z       Successfully uninstalled docutils-0.15.2
2020-07-18T03:15:49.2297786Z   Attempting uninstall: idna
2020-07-18T03:15:49.2302733Z     Found existing installation: idna 2.10
2020-07-18T03:15:49.2312032Z     Uninstalling idna-2.10:
2020-07-18T03:15:49.2896443Z       Successfully uninstalled idna-2.10
2020-07-18T03:15:49.3847665Z   Attempting uninstall: MarkupSafe
2020-07-18T03:15:49.3851620Z     Found existing installation: MarkupSafe 2.0.0a1
2020-07-18T03:15:49.3859192Z     Uninstalling MarkupSafe-2.0.0a1:
2020-07-18T03:15:49.4393101Z       Successfully uninstalled MarkupSafe-2.0.0a1
2020-07-18T03:15:49.4529312Z   Attempting uninstall: Jinja2
2020-07-18T03:15:49.4535292Z     Found existing installation: Jinja2 3.0.0a1
2020-07-18T03:15:49.4548709Z     Uninstalling Jinja2-3.0.0a1:
2020-07-18T03:15:49.5113247Z       Successfully uninstalled Jinja2-3.0.0a1
2020-07-18T03:15:51.8401954Z   Attempting uninstall: python-dateutil
2020-07-18T03:15:51.8407044Z     Found existing installation: python-dateutil 2.8.0
2020-07-18T03:15:51.8415701Z     Uninstalling python-dateutil-2.8.0:
2020-07-18T03:15:51.9030762Z       Successfully uninstalled python-dateutil-2.8.0
2020-07-18T03:15:56.3049162Z   Attempting uninstall: PyYAML
2020-07-18T03:15:56.3056093Z     Found existing installation: PyYAML 5.3.1
2020-07-18T03:15:56.3071171Z     Uninstalling PyYAML-5.3.1:
2020-07-18T03:15:56.4942687Z       Successfully uninstalled PyYAML-5.3.1
2020-07-18T03:15:58.0342729Z   Attempting uninstall: urllib3
2020-07-18T03:15:58.0348102Z     Found existing installation: urllib3 1.25.9
2020-07-18T03:15:58.0357728Z     Uninstalling urllib3-1.25.9:
2020-07-18T03:15:58.1378872Z       Successfully uninstalled urllib3-1.25.9
2020-07-18T03:15:58.2379411Z Successfully installed Babel-2.8.0 Jinja2-2.11.1 MarkupSafe-1.1.1 PyYAML-5.3 Pygments-2.5.2 Sphinx-2.3.1 alabaster-0.7.12 certifi-2019.11.28 colorama-0.4.3 dnspython-1.16.0 docutils-0.16 idna-2.8 imagesize-1.2.0 more-itertools-8.4.0 ntfsutils-0.1.4 numpy-1.18.1 oauthlib-3.1.0 packaging-20.1 pandas-1.0.1 pluggy-0.13.1 protobuf-3.6.1 psutil-5.7.0 py-1.9.0 pyparsing-2.4.6 pytest-5.4.3 python-dateutil-2.8.1 pytz-2019.3 requests-oauthlib-1.3.0 requests-toolbelt-0.9.1 six-1.14.0 snowballstemmer-2.0.0 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.2 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.3 urllib3-1.25.8 wcwidth-0.2.5
2020-07-18T03:15:58.5433096Z Traceback (most recent call last):
2020-07-18T03:15:58.5434691Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/bin/pip", line 8, in <module>
2020-07-18T03:15:58.5434969Z     sys.exit(main())
2020-07-18T03:15:58.5435877Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 75, in main
2020-07-18T03:15:58.5436115Z     return command.main(cmd_args)
2020-07-18T03:15:58.5436624Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 114, in main
2020-07-18T03:15:58.5436838Z     return self._main(args)
2020-07-18T03:15:58.5437311Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 226, in _main
2020-07-18T03:15:58.5437523Z     self.handle_pip_version_check(options)
2020-07-18T03:15:58.5438020Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 155, in handle_pip_version_check
2020-07-18T03:15:58.5438240Z     timeout=min(5, options.timeout)
2020-07-18T03:15:58.5438698Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 100, in _build_session
2020-07-18T03:15:58.5438927Z     index_urls=self._get_index_urls(options),
2020-07-18T03:15:58.5439559Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/network/session.py", line 249, in __init__
2020-07-18T03:15:58.5440075Z     self.headers["User-Agent"] = user_agent()
2020-07-18T03:15:58.5440547Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/network/session.py", line 159, in user_agent
2020-07-18T03:15:58.5440940Z     setuptools_version = get_installed_version("setuptools")
2020-07-18T03:15:58.5442026Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 634, in get_installed_version
2020-07-18T03:15:58.5442917Z     working_set = pkg_resources.WorkingSet()
2020-07-18T03:15:58.5443488Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
2020-07-18T03:15:58.5443746Z     self.add_entry(entry)
2020-07-18T03:15:58.5444264Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
2020-07-18T03:15:58.5444505Z     for dist in find_distributions(entry, True):
2020-07-18T03:15:58.5445608Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1983, in find_eggs_in_zip
2020-07-18T03:15:58.5445992Z     if metadata.has_metadata('PKG-INFO'):
2020-07-18T03:15:58.5446465Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
2020-07-18T03:15:58.5446667Z     return self._has(path)
2020-07-18T03:15:58.5447108Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1854, in _has
2020-07-18T03:15:58.5447342Z     return zip_path in self.zipinfo or zip_path in self._index()
2020-07-18T03:15:58.5447974Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1731, in zipinfo
2020-07-18T03:15:58.5448195Z     return self._zip_manifests.load(self.loader.archive)
2020-07-18T03:15:58.5449086Z   File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1688, in load
2020-07-18T03:15:58.5449470Z     mtime = os.stat(path).st_mtime
2020-07-18T03:15:58.5450317Z FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/PyYAML-5.3.1-py3.7-linux-x86_64.egg'
2020-07-18T03:15:58.5923159Z ##[error]Process completed with exit code 1.
```

**Comment by jeffshurtliff** [comment]
The required version for PyYAML has been changed to **5.3.1** in the `requirements.txt` file, which fixes the issue.
This change will be introduced in v3.0.0.
