### ISSUE TITLE
AttributeError exception when calling khoros.core.Khoros.v1.post() function without defined content type

### ISSUE THREAD

**Issue by jeffshurtliff** [jeffshurtliff/khoros#20]
**Describe the bug**
An `AttributeError` exception is returned if the `khoros.core.Khoros.v1.post` method is called without explicitly defining the `content_type` parameter.  Defining the parameter as `content_type=''` is a valid workaround.

**To Reproduce**
Call the `khoros.core.Khoros.v1.post` method without defining the `content_type` parameter, as shown below.
```python
>>> from khoros import Khoros
>>> khoros = Khoros(helper='var/khoros_helper.yml')
>>> url = '/boards/id/archer-platform-documentation/settings/name/madcap.default_doc_set/set?value=online_help'
>>> response = khoros.v1.post(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/khoros/core.py", line 699, in post
    return api.make_v1_request(self.khoros_object, endpoint, query_params, 'POST', return_json)
  File "/usr/local/lib/python3.7/site-packages/khoros/api.py", line 628, in make_v1_request
    response = post_request_with_retries(url, return_json=return_json, khoros_object=khoros_object, headers=header)
  File "/usr/local/lib/python3.7/site-packages/khoros/api.py", line 399, in post_request_with_retries
    headers=headers, multipart=multipart, content_type=content_type.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
>>> 
```

**Additional context**
The same thing happens with the `khoros.core.Khoros.post` function.

**Comment by jeffshurtliff** [comment]
Fixed the issue in v3.1.1 as demonstrated below.
```python
>>> from khoros import Khoros
>>> khoros = Khoros(helper='local/helper.yml')
>>> url = '/boards/id/archer-platform-documentation/settings/name/madcap.default_doc_set/set?value=online_help'
>>> response = khoros.v1.post(url, return_json=False)
>>> response.text
'<response status="success"/>\n'
```
