### ISSUE TITLE
Failed install with ModuleNotFoundError when installing from PyPI via pip

### ISSUE THREAD

**Issue by truthbyron** [jeffshurtliff/khoros#28]
**Describe the bug**
If you try to install the package from PyPI, it fails with an error that requests is not installed:
```
    ModuleNotFoundError: No module named 'requests'
```

**To Reproduce**
1. Create a new virtualenv, I used 3.9.1.
2. Run `python -m pip install --upgrade pip`
3. Then run `pip install khoros`
4. `pip` tries for awhile but fails.

**Expected behavior**
The egg is installed, as it is if you clone the repo and run `pip install -r requirements.txt`

**Screenshots**
Partial terminal session:
```
$ python -m pip install --upgrade pip
Collecting pip
  Using cached pip-21.0.1-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-21.0.1
$ pip install khoros
Collecting khoros
  Using cached khoros-3.3.3.tar.gz (117 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/truthbyron/.pyenv/versions/khoros-pypi/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0cpt34rr/khoros_12354d8e48c040d5bf54d71b0537739a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0cpt34rr/khoros_12354d8e48c040d5bf54d71b0537739a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-x21uszto
         cwd: /tmp/pip-install-0cpt34rr/khoros_12354d8e48c040d5bf54d71b0537739a/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0cpt34rr/khoros_12354d8e48c040d5bf54d71b0537739a/setup.py", line 6, in <module>
        import khoros.utils.version
      File "/tmp/pip-install-0cpt34rr/khoros_12354d8e48c040d5bf54d71b0537739a/khoros/__init__.py", line 13, in <module>
        from .core import Khoros
      File "/tmp/pip-install-0cpt34rr/khoros_12354d8e48c040d5bf54d71b0537739a/khoros/core.py", line 17, in <module>
        from . import auth, errors, liql, api
      File "/tmp/pip-install-0cpt34rr/khoros_12354d8e48c040d5bf54d71b0537739a/khoros/auth.py", line 12, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e1/f0/b9382658573954a0874991747a7022ff3395629b16c15c25e9aca4180765/khoros-3.3.3.tar.gz#sha256=1d2ba19a9ac1bdda5590b18c135ddca93a1e78451f35c39b8c15a56f05da6093 (from https://pypi.org/simple/khoros/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[[[snip]]]
ERROR: Could not find a version that satisfies the requirement khoros
ERROR: No matching distribution found for khoros
$
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Python 3.9.1 via pyenv and pyenv-virtualenv

**Additional context**
My guess is that it is because `setup.py` has `import khoros.utils.version` which triggers importing `requests` (among other things) but they're not installed yet. If you first run, as a distinct command before:
```
$ pip install PyYAML requests requests-toolbelt
```
then you can install `khoros` with no issues.

I hope to be able to look at the code more and provide a thoughtful PR which would fix this while melding well with the existing code, but I wanted to file this issue first so it's not lost.

**Comment by jeffshurtliff** [comment]
Thanks @truthbyron!  I really appreciate all of the detail and recommendations.  This will definitely be prioritized.

**Comment by truthbyron** [comment]
I think the problem is even a bit trickier than f0ae75bd1199. The error is happening when Python imports `khoros/__init__.py`, which then imports `core.py` which imports `auth.py` which imports requests. I refreshed my memory some from https://packaging.python.org/guides/single-sourcing-package-version/ and threw together a branch in my fork that I think fixes this a bit more, using their first method listed:

https://github.com/jeffshurtliff/khoros/compare/master...truthbyron:fix-pypi-install?expand=1

That also has a commit to move the core requirements to `setup.py` so you you get all the dependencies installed when you just do a bare pip install. Without that AFAIK it won't install the dependencies. You're welcome to rewrite/reuse/adjust/do something else or ask me for any changes/PR.

Thanks for the package, BTW.

**Comment by truthbyron** [comment]
Hey @jeffshurtliff any thoughts on this? If not, I will go ahead and make a PR based on current `master` soon to hopefully help this get resolved. Thanks!

**Comment by jeffshurtliff** [comment]
Hi Byron,

Sorry for the delay.  We launched our new community last week so things have been pretty hectic, but I hope to take another look at this in the next day or two, as I’m currently working on a new version with several other features and would love to include a fix for this along with it.

Thanks!
Jeff
