### ISSUE TITLE
Session timeout during longer operations results in 203 error code and API-related exception

### ISSUE THREAD

**Issue by jeffshurtliff** [jeffshurtliff/khoros#32]
When performing longer operations such as looping through a list of users to subscribe them to nodes, if the process takes long enough for the authentication session to timeout then it will cause the subsequent API call to potentially return a 203 error and raise one of the API-related exceptions.  This is demonstrated in the stacktrace below.

``` python
Traceback (most recent call last):
  File "adhoc/khoros/auto_subscribe.py", line 330, in <module>
    main()
  File "adhoc/khoros/auto_subscribe.py", line 293, in main
    results = subscribe_to_advisories(user_lists, opted_in_users)
  File "adhoc/khoros/auto_subscribe.py", line 264, in subscribe_to_advisories
    added_data.update(add_to_opted_in_role(user, product))
  File "adhoc/khoros/auto_subscribe.py", line 174, in add_to_opted_in_role
    response = khoros.roles.assign_roles_to_user(user, 'login', role_name)
  File "/usr/local/lib/python3.6/site-packages/khoros/core.py", line 3034, in assign_roles_to_user
    node, node_type, v1, return_json)
  File "/usr/local/lib/python3.6/site-packages/khoros/objects/roles.py", line 491, in assign_roles_to_user
    response = _assign_role_with_v2(khoros_object, user, lookup_type, roles_to_add, node, node_type)
  File "/usr/local/lib/python3.6/site-packages/khoros/objects/roles.py", line 419, in _assign_role_with_v2
    _user_id = users.get_user_id(_khoros_object, login=_user)
  File "/usr/local/lib/python3.6/site-packages/khoros/objects/users.py", line 522, in get_user_id
    user_id = _get_user_identifier(khoros_object, 'id', where_clause, allow_multiple, display_warnings)
  File "/usr/local/lib/python3.6/site-packages/khoros/objects/users.py", line 470, in _get_user_identifier
    _api_response = liql.perform_query(_khoros_object, liql_query=_liql_query, verify_success=True)
  File "/usr/local/lib/python3.6/site-packages/khoros/liql.py", line 175, in perform_query
    raise errors.exceptions.GETRequestError(error_msg)
khoros.errors.exceptions.GETRequestError: The Community API v2 call failed with the error code '203' and the following message: You are not authorized to make this request (Error Type: error_data)
```

Action needs to be taken to ensure that timed out sessions are re-initiated as necessary to prevent these failures.

**Comment by jeffshurtliff** [comment]
Closing as this project is now archived and no future updates are planned.
