### ISSUE TITLE
The khoros.categories.get_creation_date() function fails with an InvalidFieldError exception

### ISSUE THREAD

**Issue by jeffshurtliff** [jeffshurtliff/khoros#58]
## Related Function(s) or Method(s)
> **Note:** You can assume that the core object has been instantiated as `khoros` when listing them below.
- `khoros.Category.get_creation_date`
- `khoros.objects.categories.get_creation_date`

## Details
Attempts to call the `get_creation_date()` function fail with an `InvalidFieldError` exception.

## Steps to Reproduce
``` python
from khoros import Khoros
khoros = Khoros(helper='local/stage_helper.yml')
khoros.categories.get_creation_date('support')
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/shurtj/Development/khoros/khoros/core.py", line 2184, in get_creation_date
    return structures_module.categories.get_creation_date(self.khoros_object, identifier, category_details)
  File "/Users/shurtj/Development/khoros/khoros/structures/categories.py", line 528, in get_creation_date
    return get_category_field(khoros_object, 'get_creation_date', identifier, category_details)
  File "/Users/shurtj/Development/khoros/khoros/structures/categories.py", line 149, in get_category_field
    return base.get_structure_field(khoros_object, field, identifier, structure_type='category',
  File "/Users/shurtj/Development/khoros/khoros/structures/base.py", line 211, in get_structure_field
    raise errors.exceptions.InvalidFieldError(val=field)
khoros.errors.exceptions.InvalidFieldError: The 'get_creation_date' field that was provided is invalid.
```

## Expected Behavior
Should return the timestamp.

**Comment by jeffshurtliff** [comment]
Issue is resolved in v5.1.0 which is now GA.
