### ISSUE TITLE
khoros.categories.get_parent_id fails with a KeyError exception on top-level categories

### ISSUE THREAD

**Issue by jeffshurtliff** [jeffshurtliff/khoros#59]
## Related Function(s) or Method(s)
> **Note:** You can assume that the core object has been instantiated as `khoros` when listing them below.
- `khoros.core.Khoros.Category.get_parent_id`
- `khoros.objects.categories.get_parent_id`

## Details
When calling the `get_parent_id()` function or method with a top-level category as a parameter, the call fails with a `KeyError` exception.

## Steps to Reproduce
``` python
>>> khoros.categories.get_parent_id('product-support')
'support'
>>> khoros.categories.get_parent_id('support')
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/shurtj/Development/khoros/khoros/core.py", line 1962, in get_parent_id
    return structures_module.categories.get_parent_id(self.khoros_object, identifier, category_details)
  File "/Users/shurtj/Development/khoros/khoros/structures/categories.py", line 267, in get_parent_id
    return get_category_field(khoros_object, 'parent_id', identifier, category_details)
  File "/Users/shurtj/Development/khoros/khoros/structures/categories.py", line 149, in get_category_field
    return base.get_structure_field(khoros_object, field, identifier, structure_type='category',
  File "/Users/shurtj/Development/khoros/khoros/structures/base.py", line 216, in get_structure_field
    return_field = details[api_field[0]][api_field[1]]
KeyError: 'id'
```

## Expected Behavior
The function/method should not raise an exception.

## Suggestions or Proposals
The value returned should be the tenant ID to indicate that its parent is the root level.

**Comment by jeffshurtliff** [comment]
This fix has been introduced in v5.1.1 which is now GA.
